image:
  broker:
    repository: datastax/lunastreaming-all
    pullPolicy: IfNotPresent
    tag: 2.10_3.1
  brokerSts:
    repository: datastax/lunastreaming-all
    pullPolicy: IfNotPresent
    tag: 2.10_3.1
  function:
    repository: datastax/lunastreaming-all
    pullPolicy: IfNotPresent
    tag: 2.10_3.1
  zookeeper:
    repository: datastax/lunastreaming-all
    pullPolicy: IfNotPresent
    tag: 2.10_3.1
  bookkeeper:
    repository: datastax/lunastreaming-all
    pullPolicy: IfNotPresent
    tag: 2.10_3.1
  proxy:
    repository: datastax/lunastreaming-all
    pullPolicy: IfNotPresent
    tag: 2.10_3.1
  bastion:
    repository: datastax/lunastreaming-all
    pullPolicy: IfNotPresent
    tag: 2.10_3.1

fullnameOverride: mypulsar
enableAntiAffinity: true
enableTls: false
enableTokenAuth: true
restartOnConfigMapChange:
  enabled: true
extra:
  broker: true
  brokerSts: false
  function: true
  burnell: true
  burnellLogCollector: true
  pulsarHeartbeat: true
  pulsarAdminConsole: true

cert-manager:
  enabled: true

createCertificates:
  selfSigned:
    enabled: true

zookeeper:
  replicaCount: 3
  resources:
    requests:
      memory: 512Mi
      cpu: 0.5
  configData:
    PULSAR_MEM: "-Xms512m -Xmx512m -Djute.maxbuffer=10485760 -XX:+ExitOnOutOfMemoryError"
  volumes:
    data:
      name: data
      size: 2Gi

bookkeeper:
  replicaCount: 2
  resources:
    requests:
      memory: 1024Mi
      cpu: 0.5
  volumes:
    journal:
      name: journal
      size: 2Gi
    ledgers:
      name: ledgers
      size: 5Gi
  configData:
    BOOKIE_MEM: "-Xms800m -Xmx800m -XX:MaxDirectMemorySize=224m -XX:+ExitOnOutOfMemoryError"

broker:
  component: broker
  replicaCount: 2
  service:
    type: ClusterIP
    headless: false
    ports:
      - name: http
        port: 8080
      - name: pulsar
        port: 6650
      - name: kafkaplaintext
        port: 9092
      - name: kafkaschemareg
        port: 8081
  ledger:
    defaultEnsembleSize: 1
    defaultAckQuorum: 1
    defaultWriteQuorum: 1
  resources:
    requests:
      memory: 1024Mi
      cpu: 1.0
  configData:
    PULSAR_MEM: "-Xms800m -Xmx800m -XX:MaxDirectMemorySize=224m -XX:+ExitOnOutOfMemoryError"
    transactionCoordinatorEnabled: "true"
    brokerDeleteInactiveTopicsEnabled: "false"
    allowAutoTopicCreationType: "partitioned"
    PULSAR_PREFIX_protocolHandlerDirectory: "./protocols"
    PULSAR_PREFIX_messagingProtocols: "kafka"
    PULSAR_PREFIX_brokerEntryMetadataInterceptors: "org.apache.pulsar.common.intercept.AppendIndexMetadataInterceptor,org.apache.pulsar.common.intercept.AppendBrokerTimestampMetadataInterceptor"
    PULSAR_PREFIX_kafkaTransactionCoordinatorEnabled: "true"
    PULSAR_PREFIX_kopSchemaRegistryEnable: "true"
    PULSAR_PREFIX_saslAllowedMechanisms: PLAIN
    PULSAR_PREFIX_kafkaListeners: "SASL_PLAINTEXT://0.0.0.0:9092"
    ## This line is required
    PULSAR_PREFIX_kafkaAdvertisedListeners: "SASL_PLAINTEXT://advertisedAddress:9092"

autoRecovery:
  enableProvisionContainer: true
  resources:
    requests:
      memory: 500Mi
      cpu: 0.5

function:
  replicaCount: 1
  functionReplicaCount: 1
  resources:
    requests:
      memory: 512Mi
      cpu: 0.5
  volumes:
    data:
      name: logs
      size: 1Gi
  configData:
    PULSAR_MEM: "-Xms400m -Xmx400m -XX:MaxDirectMemorySize=112m -XX:+ExitOnOutOfMemoryError"

proxy:
  replicaCount: 1
  resources:
    requests:
      memory: 512Mi
      cpu: 0.5
  wsResources:
    requests:
      memory: 512Mi
      cpu: 0.5
  configData:
    PULSAR_MEM: "-Xms400m -Xmx400m -XX:MaxDirectMemorySize=112m"
    PULSAR_PREFIX_kopSchemaRegistryEnable: "true"
    PULSAR_PREFIX_kopSchemaRegistryProxyPort: "8081"
    PULSAR_PREFIX_kafkaTransactionCoordinatorEnabled: "true"
    PULSAR_PREFIX_saslAllowedMechanisms: PLAIN
    PULSAR_PREFIX_kafkaProxySuperUserRole: superuser
    PULSAR_PREFIX_kafkaListeners: "SASL_PLAINTEXT://0.0.0.0:9092"
    # if you use port forwarding to localhost then you have to set 'localhost'    
    PULSAR_PREFIX_kafkaAdvertisedListeners: "SASL_PLAINTEXT://localhost:9092"
  service:
    autoPortAssign:
      enabled: true
  extensions:
    enabled: true
    extensions: "kafka"
    containerPorts:
      - name: kafkaplaintext
        containerPort: 9092
      - name: kafkaschemareg
        containerPort: 8081
    servicePorts:
     - name: kafkaplaintext
       port: 9092
       protocol: TCP
       targetPort: kafkaplaintext
     - name: kafkaschemareg
       port: 8081
       protocol: TCP
       targetPort: kafkaschemareg

pulsarAdminConsole:
  replicaCount: 1
  resources:
    requests:
      memory: 512Mi
      cpu: 0.5

grafanaDashboards:
  enabled: true

kube-prometheus-stack:
  enabled: true
  prometheusOperator:
    enabled: false
  nodeExporter:
    enabled: false
  grafana:
    enabled: true
    adminPassword: e9JYtk83*4#PM8